[package]
name = "notenoughminerals-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

rs-graph = { version = "0.21.0-dev", path = "/home/fifr/projekte/rust/rs-graph" }
