[package]
name = "supply-stacks-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "^1"
lazy_static = "^1"

[[bin]]
name = "supply-stacks1"

[[bin]]
name = "supply-stacks2"
